### PR TITLE
modeling code

### PR DESCRIPTION
**Pull request by catarfish**
So pulling from the clean daymet dataset, we found some issues that Shruti said you had worked on before with the leap year. We need to have data for everyday to use our rollapply function, so can you either directly make edits or let me know how to fix it so that we have data for every day in our covariates? I can also talk to lauren et al if they already have a clean covars dataset. 

The rest of these edits are made so that we have something to present for monday. we are still using the original datasets for now until we fix that and get liz's clean chlorophyll back up (i think it got deleted) so if it looks okay ayou could just merge this for now so pascale can access it that would be great and we can work on leap years separately. Thanks!!

### CODE REVIEW

**Comment by ryanpeek** [comment]
@catarfish I will try to get to this today and either merge or fix and merge. I'll ping you either way when it's done!

**Comment by ryanpeek** [comment]
@catarfish so I looked at `f_load_gam_data` and I think there are two potential issues. Neither has to do with leap years...

- when joining all the data together (line 66ish), we are adding duplicate dates because we are using `full_join` here. Which is fine, because we want to keep all the chl-a data, of which there are multiple measurements from the same date (but different stations) in many cases. 
- But what this means is when you try to `rollapply` over the dates, you are creating a non-uniform moving window in some cases because it's looking at 7 rows as always = to a week...but that isn't always the case because of the duplicate dates.

## Solutions!

I pushed a potential workaround, but not sure it's exactly what you want. You can either:

 1. do your rollapply on the distinct data pieces FIRST, then join everything together
 2. join all data EXCEPT the chl-a piece, make sure you have a distinct series of dates (i.e., everything should equal 8708), and then join with chl-a data (and have the duplicated dates and associated covariate data).

Hope this makes sense! Take a look and let me know what you think.

**Comment by catarfish** [comment]
Hey Ryan, so I copied and pasted in your changes. Will make a few tweaks afterwards once the chla data are ready. Go ahead and merge in. Thanks for fixing!

**Comment by ryanpeek** [comment]
looks good @catarfish and I added the chla_dataset in the`model_dataset`...it's a little different so will want to double check and replace the data pieces, but it merges all the flow, inundation, and day met data in with the chla data we pulled for yolo.

**Review by ryanpeek — COMMENTED** [review]
Great!

**Pull request merged**
